### ISSUE TITLE
Binary payload

### ISSUE THREAD

**Issue by fredy2015** [abhishek-ram/pyas2#26]
Hi,

At the moment, we can't use pyas2 with one of our client because signing failed with binary payload. Is Could you implement binary payload?

Thanks

**Comment by abhishek-ram** [comment]
Can you please elaborate as to what is the error that you are getting and so on.

**Comment by Vio-san** [comment]
I believe it's related to \r\n canonicalization within MIME message. According to RFC3851 and RFC5751 for binary data that can not be canonicalized due to data modification related to it you need to utilize 7bit compatible encoding like base64. It can be solved by having a checkbox in partner settings with a name like "Is it safe to perform canonicalization?" and according to RFC should be based on an agreement between organization and partner. In this way, it will not conflict with RFC3851. Another option is to have complex canonicalization algorithm that will canonicalize only headers for the document part and full content for the signature and encrypted data.

**Comment by abhishek-ram** [comment]
AS2 was never meant for transferring binary payload so I never factored this in when I developed pyas2. The current process is very convoluted so I have started working on a separate project which only handles building/parsing the MIME messages. I will test there with binary payloads and see what will be the result.
